### PR TITLE
Add libignition-tools1 to fix build warning

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please restart builds

**Comment by traversaro** [comment]
I wonder if we should make ruby a run depending of `libignition-tools`, as it is necessary to run the `ign` commands.

**Comment by Tobias-Fischer** [comment]
Agreed @traversaro. If my latest commit fixes the test failure, that is probably the way to go.

**Comment by Tobias-Fischer** [comment]
See https://github.com/conda-forge/libignition-tools-feedstock/pull/4

**Comment by wolfv** [comment]
should we wait with this one for the libignition-tools?

**Comment by wolfv** [comment]
I added automerge :)

**Pull request merged**
