### PR TITLE
REF change version to match the upstream tag

### PR DESCRIPTION
**Pull request by beckermr**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by beckermr** [comment]
@conda-forge-admin rerender

**Review by traversaro — APPROVED** [review]
Thanks @beckermr !

**Comment by traversaro** [comment]
@Tobias-Fischer are you ok in merging this? The idea is that then I will propagate a similar change to the rest of ignition feedstock.

**Comment by wolfv** [comment]
~~hmm, wouldn't it be better to fix the ticker bot to figure out the `{% set version =...` stuff and propagate that?~~

EDIT ah ok, I see. since the release comes from github the version is taken from some sort of feed and therefore we get the proper tag from upstream.

**Comment by beckermr** [comment]
Right. We strip all characters at the start of tags, for better or worse.

**Review by Tobias-Fischer — APPROVED** [review]

**Review by traversaro — APPROVED** [review]
Thanks @beckermr !

**Pull request merged**
